version: '3.8'
services:
  server:
    build: ./FitHub.Server
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  client:
    build: ./fithub.client
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'FitHub'
      # MYSQL_USER: 'your_user'
      # MYSQL_PASSWORD: 'your_password'
      # MYSQL_ROOT_PASSWORD: 'your_root_password'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: